k3s_version: v1.28.5+k3s1
# Generate with: openssl rand -hex 32
# Or on Windows: $token = -join ((1..64 | ForEach-Object { '{0:X}' -f (Get-Random -Max 16) })) && Write-Host "Your k3s token: $token"
k3s_token: "97A6ABCFF7506835173C0D7422FBB27230E96644CA9A1A740FD9C4F9EC1CEB76"
ansible_user: chipfox
# systemd_dir: /etc/systemd/system
